# Rename this file to languages.toml to enable multilingual support
[vi]
languageName = "Tiếng Việt"
languagedirection = "ltr"
title = "Hoàng Dương"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "Hoang Duong"
weight = 2