# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"

#[main.params]
#icon = "home"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/HoangDuonng"


[social.params]
icon = "brand-github"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/ngu_uuen/"

[social.params]
icon = "brand-instagram"
